// 광고주
export const FETCH_GET_NEWS_FEED_ADVERTISER = 'FETCH_GET_NEWS_FEED_ADVERTISER';

// 마케터
export const FETCH_GET_GOOGLE_CSV_DOWNLOAD = 'FETCH_GET_GOOGLE_CSV_DOWNLOAD';
export const FETCH_GET_ADS = 'FETCH_GET_ADS';
export const FETCH_SELECT_ADS = 'FETCH_SELECT_ADS';
export const FETCH_SELECT_ACCOUNT_ID = 'FETCH_SELECT_ACCOUNT_ID';
export const FETCH_GET_HORIZONTAL_CHART = 'FETCH_GET_HORIZONTAL_CHART';
export const FETCH_GET_CAMPAIGN = 'FETCH_GET_CAMPAIGN';
export const FETCH_GET_SELECT_CAMPAIGN = 'FETCH_GET_SELECT_CAMPAIGN';
export const FETCH_GET_CAMPAIGN_LINE_CHART = 'FETCH_GET_CAMPAIGN_LINE_CHART';
export const FETCH_GET_CAMPAIGN_CANDLE_CHART = 'FETCH_GET_CAMPAIGN_CANDLE_CHART';
export const FETCH_GET_CAMPAIGN_PURCHASE_FLOW_CHART = 'FETCH_GET_CAMPAIGN_PURCHASE_FLOW_CHART';
export const FETCH_GET_CAMPAIGN_ADS_SET_TABLE = 'FETCH_GET_CAMPAIGN_ADS_SET_TABLE';
export const FETCH_GET_CAMPAIGN_ADS_SET_DROPDOWN_TABLE = 'FETCH_GET_CAMPAIGN_ADS_SET_DROPDOWN_TABLE';
export const FETCH_GET_CAMPAIGN_AD_TABLE = 'FETCH_GET_CAMPAIGN_AD_TABLE';
export const FETCH_GET_CAMPAIGN_AD_DROPDOWN_TABLE = 'FETCH_GET_CAMPAIGN_AD_DROPDOWN_TABLE';
export const FETCH_GET_CAMPAIGN_AGE_CHART = 'FETCH_GET_CAMPAIGN_AGE_CHART';
export const FETCH_GET_CAMPAIGN_GENDER_CHART = 'FETCH_GET_CAMPAIGN_GENDER_CHART';
export const FETCH_GET_CAMPAIGN_AGE_GENDER_CHART = 'FETCH_GET_CAMPAIGN_AGE_GENDER_CHART';
export const FETCH_GET_CAMPAIGN_LOCATION_MAP = 'FETCH_GET_CAMPAIGN_LOCATION_MAP';
export const FETCH_GET_NEWS_FEED = 'FETCH_GET_NEWS_FEED';
export const FETCH_GET_AD_SEND = 'FETCH_GET_AD_SEND';
export const FETCH_GET_MY_ADS = 'FETCH_GET_MY_ADS';
