// Advertiser
export const FETCH_ADVERTISER_STATE = 'FETCH_ADVERTISER_STATE';
export const FETCH_GET_CREATE_AD = 'FETCH_GET_CREATE_AD';
export const FETCH_FACEBOOK_BUSINESS_INFO = 'FETCH_FACEBOOK_BUSINESS_INFO';
export const FETCH_FACEBOOK_PAGE_INFO = 'FETCH_FACEBOOK_PAGE_INFO';
export const FETCH_ADVERTISER_PAYMENT_HISTORY = 'FETCH_ADVERTISER_PAYMENT_HISTORY';

// Marketer
export const FETCH_USER_STATE = 'FETCH_USER_STATE';
export const FETCH_USER_PERSONAL_INFO = 'FETCH_USER_PERSONAL_INFO';
export const FETCH_USER_GOOGLE_LOGIN = 'FETCH_USER_GOOGLE_LOGIN';
export const FETCH_USER_FACEBOOK_LOGIN = 'FETCH_USER_FACEBOOK_LOGIN';
export const FETCH_GET_SOCIAL_ACCOUNT = 'FETCH_GET_SOCIAL_ACCOUNT';
export const FETCH_USER_LOGOUT = 'FETCH_USER_LOGOUT';
export const FETCH_RESET_PASSWORD = 'FETCH_RESET_PASSWORD';
export const FETCH_QNA = 'FETCH_QNA';
export const FETCH_MY_REVENUE = 'FETCH_MY_REVENUE';
export const FETCH_MY_RANKING = 'FETCH_MY_RANKING';
export const FETCH_MARKETER_DETAILS = 'FETCH_MARKETER_DETAILS';
export const FETCH_BUSINESS_DETAILS = 'FETCH_BUSINESS_DETAILS';
