export const FETCH_UPLOAD_IMAGE = 'FETCH_UPLOAD_IMAGE';
export const FETCH_UPLOAD_VIDEO = 'FETCH_UPLOAD_VIDEO';
export const FETCH_UPLOAD_SEARCH = 'FETCH_UPLOAD_SEARCH';
export const FETCH_UPLOAD_FAIL = 'FETCH_UPLOAD_FAIL';
